export const products = [
    {
        id: 1,
        name: 'Jeep Wrangler Rubicon',
        price: '$384.990.000',
        inStock: 1,
        description: 'Carro Jeep Wrangler Rubicon',
        img: 'https://www.carscoops.com/wp-content/uploads/2020/08/Jeep-Wrangler-Rubicon-Recon-1a.jpg',
        categoryId: 1,
    },
    {
        id: 2,
        name: 'Toyota Hilux',
        price: '$28.880',
        inStock: 2,
        description: 'Carro Toyota Hilux color rojo',
        img: 'https://www.megautos.com/wp-content/uploads/2021/08/Toyota-Hilux-GR-Sport-2022-roja.jpg',
        categoryId: 1,
    },
    {
        id: 3,
        name: 'Sportster S™ 2023',
        price: '$20.507',
        inStock: 5,
        description: 'Moto Sportster S™ 2023',
        img: 'https://www.harley-davidson.com/content/dam/h-d/images/product-images/bikes/motorcycle/2023/2023-sportster-s/2023-sportster-s-f89/2023-sportster-s-f89-motorcycle.jpg?impolicy=myresize&rw=500',
        categoryId: 1,
    },
    {
        id: 4,
        name: 'Xiaomi 13T Negro',
        price: '$609',
        inStock: 5,
        description: 'Xiaomi 13T Negro 256GB+12GB RAM',
        img: 'https://xiaomioficial.pe/media/catalog/product/cache/9b5812cc5db82aed36978fe8f1f098e1/0/-/0-xiaomi-comprar-xiaomi-13t-256gb-telefono-celular-smartphone-oferta_1.png',
        categoryId: 2,
    },
    {
        id: 5,
        name: 'LG OLED evo',
        price: '$3314',
        inStock: 2,
        description: 'LG OLED evo 77" G3 Diseño Galería 4K Smart TV con ThinQ AI (Inteligencia Artificial)',
        img: 'https://www.purepc.pl/image/news/2023/01/03_lg_oled_g3_tegoroczny_telewizor_4k_z_panelem_oled_evo_zaoferuje_szczytowa_jasnosc_siegajaca_ponad_2000_nitow_1_b.jpg',
        categoryId: 2,
    },
    {
        id: 6,
        name: 'ROG Zephyrus',
        price: '$4639',
        inStock: 10,
        description: 'Laptop Asus ROG Zephyrus',
        img: 'https://www.asus.com/media/Odin/Websites/global/ProductLine/20200824120814.jpg?webp',
        categoryId: 2,
    },
    {
        id: 7,
        name: 'Diario de Greg',
        price: '$10',
        inStock: 5,
        description: 'Diario de Greg un pringao total',
        img: 'https://imagessl0.casadellibro.com/a/l/t0/20/9788498672220.jpg',
        categoryId: 3,
    },
    {
        id: 8,
        name: 'Emily the strange',
        price: '$15',
        inStock: 7,
        description: 'Emily the strange tiempos oscuros',
        img: 'https://www.agapea.com/Fundacion-Santa-Maria-Ediciones-SM/Emily-the-Strange-Tiempos-oscuros-i6n2220947.jpg',
        categoryId: 3,
    },
    {
        id: 9,
        name: 'Divina comedia',
        price: '$20',
        inStock: 2,
        description: 'Divina comedia infierno',
        img: 'https://image.isu.pub/210601123820-d2132435a60ea9f669d84c71b719131c/jpg/page_1.jpg',
        categoryId: 3,
    },
]